application: abetterportfolio
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: css
  
- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /
  script: home.app

- url: /test_home
  script: home.app

- url: /home
  script: home.app

- url: /projects
  script: home.app

- url: /experience
  script: home.app

- url: /education
  script: home.app

- url: /github_activity
  script: home.app
 
- url: /.*
  static_files: allhtml/404.html
  upload: allhtml/404.html

libraries:
- name: jinja2
  version: latest
  
- name: webapp2
  version: "2.5.1"