application: abetterportfolio
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: .*
  script: helloworld.app

libraries:
- name: jinja2
  version: latest
  
- name: webapp2
  version: "2.5.1"