import httplib2
import webapp2
import os
import jinja2
import json
from apiclient.discovery import build
from oauth2client.appengine import AppAssertionCredentials
from utils import get_gist_data
from GitHubActivityUtil import *
from github_archive_bigquery_handler import *
from github_archive_parser import *

credentials = AppAssertionCredentials(scope='https://www.googleapis.com/auth/bigquery')
http = credentials.authorize(httplib2.Http())

template_dir = os.path.join(os.path.dirname(__file__), 'allhtml')
jinja_env = jinja2.Environment(loader = jinja2.FileSystemLoader(template_dir), autoescape = True)



archive = { "etag" : "\"NZ75KOpnCp1s2IAQ18M09x_sP8o/KcQsQ0FhkLKU4KWFwPWeyBrT45w\"",
  "kind" : "bigquery#tableDataList",
  "pageToken" : "85@1348195423683",
  "rows" : [ { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "android" },
            { "v" : "https://github.com/github/android" },
            { "v" : "GitHub Android App" },
            { "v" : "Java" },
            { "v" : "https://github.com/github/android/issues/229#issuecomment-8711619" },
            { "v" : "2012-09-19 23:00:25" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "android" },
            { "v" : "https://github.com/github/android" },
            { "v" : "GitHub Android App" },
            { "v" : "Java" },
            { "v" : "https://github.com/github/android/issues/229#issuecomment-8704437" },
            { "v" : "2012-09-19 19:58:45" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "android" },
            { "v" : "https://github.com/github/android" },
            { "v" : "GitHub Android App" },
            { "v" : "Java" },
            { "v" : "https://github.com/github/android/issues/229#issuecomment-8704251" },
            { "v" : "2012-09-19 19:52:45" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "version.is" },
            { "v" : "https://github.com/gustavnikolaj/version.is" },
            { "v" : "version.is: Single-page app and API for version checking of Open Source projects" },
            { "v" : "Python" },
            { "v" : "https://github.com/gustavnikolaj/version.is/issues/17#issuecomment-8690755" },
            { "v" : "2012-09-19 13:22:33" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/86#issuecomment-8678959" },
            { "v" : "2012-09-19 04:25:50" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/86#issuecomment-8667852" },
            { "v" : "2012-09-18 19:51:09" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "version.is" },
            { "v" : "https://github.com/gustavnikolaj/version.is" },
            { "v" : "version.is: Single-page app and API for version checking of Open Source projects" },
            { "v" : "Python" },
            { "v" : "https://github.com/gustavnikolaj/version.is/issues/5#issuecomment-8656929" },
            { "v" : "2012-09-18 14:37:26" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "version.is" },
            { "v" : "https://github.com/gustavnikolaj/version.is" },
            { "v" : "version.is: Single-page app and API for version checking of Open Source projects" },
            { "v" : "Python" },
            { "v" : "https://github.com/gustavnikolaj/version.is/issues/5#issuecomment-8655315" },
            { "v" : "2012-09-18 13:48:36" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "version.is" },
            { "v" : "https://github.com/gustavnikolaj/version.is" },
            { "v" : "version.is: Single-page app and API for version checking of Open Source projects" },
            { "v" : "Python" },
            { "v" : "https://github.com/gustavnikolaj/version.is/issues/5#issuecomment-8653003" },
            { "v" : "2012-09-18 12:46:40" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "version.is" },
            { "v" : "https://github.com/gustavnikolaj/version.is" },
            { "v" : "version.is: Single-page app and API for version checking of Open Source projects" },
            { "v" : "Python" },
            { "v" : "https://github.com/gustavnikolaj/version.is/issues/5#issuecomment-8651787" },
            { "v" : "2012-09-18 12:16:48" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/86#issuecomment-8638751" },
            { "v" : "2012-09-18 03:20:04" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "version.is" },
            { "v" : "https://github.com/gustavnikolaj/version.is" },
            { "v" : "version.is: Single-page app and API for version checking of Open Source projects" },
            { "v" : "Python" },
            { "v" : "https://github.com/gustavnikolaj/version.is/issues/5#issuecomment-8637719" },
            { "v" : "2012-09-18 02:19:00" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "version.is" },
            { "v" : "https://github.com/gustavnikolaj/version.is" },
            { "v" : "version.is: Single-page app and API for version checking of Open Source projects" },
            { "v" : "Python" },
            { "v" : "https://github.com/gustavnikolaj/version.is/issues/5#issuecomment-8637552" },
            { "v" : "2012-09-18 02:09:27" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "version.is" },
            { "v" : "https://github.com/gustavnikolaj/version.is" },
            { "v" : "version.is: Single-page app and API for version checking of Open Source projects" },
            { "v" : "Python" },
            { "v" : "https://github.com/gustavnikolaj/version.is/issues/8#issuecomment-8630511" },
            { "v" : "2012-09-17 20:54:14" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "version.is" },
            { "v" : "https://github.com/gustavnikolaj/version.is" },
            { "v" : "version.is: Single-page app and API for version checking of Open Source projects" },
            { "v" : "Python" },
            { "v" : "https://github.com/gustavnikolaj/version.is/issues/11#issuecomment-8616302" },
            { "v" : "2012-09-17 14:23:43" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "version.is" },
            { "v" : "https://github.com/gustavnikolaj/version.is" },
            { "v" : "version.is: Single-page app and API for version checking of Open Source projects" },
            { "v" : "Python" },
            { "v" : "https://github.com/gustavnikolaj/version.is/issues/11#issuecomment-8616059" },
            { "v" : "2012-09-17 14:19:22" }
          ] },
      { "f" : [ { "v" : "IssuesEvent" },
            { "v" : "sagarsane" },
            { "v" : "opened" },
            { "v" : "" },
            { "v" : "version.is" },
            { "v" : "https://github.com/gustavnikolaj/version.is" },
            { "v" : "version.is: Single-page app and API for version checking of Open Source projects" },
            { "v" : "Python" },
            { "v" : "https://github.com/gustavnikolaj/version.is/issues/11" },
            { "v" : "2012-09-17 01:11:18" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/86#issuecomment-8601833" },
            { "v" : "2012-09-16 23:56:22" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/86#issuecomment-8597355" },
            { "v" : "2012-09-16 18:21:01" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/86#issuecomment-8596908" },
            { "v" : "2012-09-16 17:40:20" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/86#issuecomment-8596166" },
            { "v" : "2012-09-16 16:21:02" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "android" },
            { "v" : "https://github.com/github/android" },
            { "v" : "GitHub Android App" },
            { "v" : "Java" },
            { "v" : "https://github.com/github/android/issues/222#issuecomment-8591896" },
            { "v" : "2012-09-16 03:10:49" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "android" },
            { "v" : "https://github.com/github/android" },
            { "v" : "GitHub Android App" },
            { "v" : "Java" },
            { "v" : "https://github.com/github/android/issues/222#issuecomment-8591535" },
            { "v" : "2012-09-16 01:59:06" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/96#issuecomment-8541227" },
            { "v" : "2012-09-13 20:02:37" }
          ] },
      { "f" : [ { "v" : "IssuesEvent" },
            { "v" : "sagarsane" },
            { "v" : "opened" },
            { "v" : "" },
            { "v" : "version.is" },
            { "v" : "https://github.com/gustavnikolaj/version.is" },
            { "v" : "version.is: Single-page app and API for version checking of Open Source projects" },
            { "v" : "Python" },
            { "v" : "https://github.com/gustavnikolaj/version.is/issues/8" },
            { "v" : "2012-09-13 18:01:42" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/96#issuecomment-8537109" },
            { "v" : "2012-09-13 17:58:31" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/issues/1599#issuecomment-8536311" },
            { "v" : "2012-09-13 17:33:29" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/96#issuecomment-8536152" },
            { "v" : "2012-09-13 17:28:22" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/96#issuecomment-8534454" },
            { "v" : "2012-09-13 16:35:56" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "version.is" },
            { "v" : "https://github.com/gustavnikolaj/version.is" },
            { "v" : "version.is: Single-page app and API for version checking of Open Source projects" },
            { "v" : "Python" },
            { "v" : "https://github.com/gustavnikolaj/version.is/issues/3#issuecomment-8531840" },
            { "v" : "2012-09-13 15:19:03" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/issues/1598#issuecomment-8503337" },
            { "v" : "2012-09-12 17:41:14" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/96#issuecomment-8503185" },
            { "v" : "2012-09-12 17:36:54" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/96#issuecomment-8495254" },
            { "v" : "2012-09-12 14:25:17" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "PyGithub" },
            { "v" : "https://github.com/jacquev6/PyGithub" },
            { "v" : "Python library implementing the full Github API v3" },
            { "v" : "Python" },
            { "v" : "https://github.com/jacquev6/PyGithub/issues/82#issuecomment-8494716" },
            { "v" : "2012-09-12 14:09:46" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/86#issuecomment-8481792" },
            { "v" : "2012-09-12 04:27:59" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/86#issuecomment-8481457" },
            { "v" : "2012-09-12 04:05:31" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/issues/1568#issuecomment-8465467" },
            { "v" : "2012-09-11 17:21:42" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/86#issuecomment-8459797" },
            { "v" : "2012-09-11 13:38:57" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/86#issuecomment-8446860" },
            { "v" : "2012-09-11 04:36:24" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/86#issuecomment-8446340" },
            { "v" : "2012-09-11 03:53:15" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/issues/1597#issuecomment-8444690" },
            { "v" : "2012-09-11 01:55:07" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/86#issuecomment-8435011" },
            { "v" : "2012-09-10 19:21:19" }
          ] },
      { "f" : [ { "v" : "PullRequestReviewCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/pull/1599#discussion_r1568385" },
            { "v" : "2012-09-10 17:36:33" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "jquery-pjax" },
            { "v" : "https://github.com/defunkt/jquery-pjax" },
            { "v" : "pushState + ajax = pjax" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/defunkt/jquery-pjax/issues/184#issuecomment-8426208" },
            { "v" : "2012-09-10 15:18:33" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "jquery-pjax" },
            { "v" : "https://github.com/defunkt/jquery-pjax" },
            { "v" : "pushState + ajax = pjax" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/defunkt/jquery-pjax/issues/184#issuecomment-8425244" },
            { "v" : "2012-09-10 14:55:07" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "jquery-pjax" },
            { "v" : "https://github.com/defunkt/jquery-pjax" },
            { "v" : "pushState + ajax = pjax" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/defunkt/jquery-pjax/issues/181#issuecomment-8410922" },
            { "v" : "2012-09-10 00:04:47" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "jquery-pjax" },
            { "v" : "https://github.com/defunkt/jquery-pjax" },
            { "v" : "pushState + ajax = pjax" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/defunkt/jquery-pjax/issues/181#issuecomment-8410250" },
            { "v" : "2012-09-09 22:39:46" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "jquery-pjax" },
            { "v" : "https://github.com/defunkt/jquery-pjax" },
            { "v" : "pushState + ajax = pjax" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/defunkt/jquery-pjax/issues/181#issuecomment-8410212" },
            { "v" : "2012-09-09 22:35:13" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "jquery-pjax" },
            { "v" : "https://github.com/defunkt/jquery-pjax" },
            { "v" : "pushState + ajax = pjax" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/defunkt/jquery-pjax/issues/181#issuecomment-8409789" },
            { "v" : "2012-09-09 21:50:27" }
          ] },
      { "f" : [ { "v" : "PullRequestReviewCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/pull/1599#discussion_r1561449" },
            { "v" : "2012-09-09 04:44:50" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/issues/1599#issuecomment-8397297" },
            { "v" : "2012-09-08 20:04:01" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "jquery-pjax" },
            { "v" : "https://github.com/defunkt/jquery-pjax" },
            { "v" : "pushState + ajax = pjax" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/defunkt/jquery-pjax/issues/181#issuecomment-8391206" },
            { "v" : "2012-09-08 16:52:12" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "jquery-pjax" },
            { "v" : "https://github.com/defunkt/jquery-pjax" },
            { "v" : "pushState + ajax = pjax" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/defunkt/jquery-pjax/issues/181#issuecomment-8388359" },
            { "v" : "2012-09-08 15:00:55" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "jquery-pjax" },
            { "v" : "https://github.com/defunkt/jquery-pjax" },
            { "v" : "pushState + ajax = pjax" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/defunkt/jquery-pjax/issues/181#issuecomment-8387596" },
            { "v" : "2012-09-08 13:30:37" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/issues/1598#issuecomment-8384978" },
            { "v" : "2012-09-08 06:14:58" }
          ] },
      { "f" : [ { "v" : "PullRequestEvent" },
            { "v" : "sagarsane" },
            { "v" : "opened" },
            { "v" : "Added search query in search results label for 'Find In Files'" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/pull/1599" },
            { "v" : "2012-09-08 06:13:55" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/issues/1598#issuecomment-8384917" },
            { "v" : "2012-09-08 06:01:03" }
          ] },
      { "f" : [ { "v" : "IssuesEvent" },
            { "v" : "sagarsane" },
            { "v" : "opened" },
            { "v" : "" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/issues/1598" },
            { "v" : "2012-09-08 05:31:23" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/issues/1597#issuecomment-8384745" },
            { "v" : "2012-09-08 05:25:36" }
          ] },
      { "f" : [ { "v" : "IssuesEvent" },
            { "v" : "sagarsane" },
            { "v" : "opened" },
            { "v" : "" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/issues/1597" },
            { "v" : "2012-09-08 05:12:58" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "jquery-pjax" },
            { "v" : "https://github.com/defunkt/jquery-pjax" },
            { "v" : "pushState + ajax = pjax" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/defunkt/jquery-pjax/issues/181#issuecomment-8383760" },
            { "v" : "2012-09-08 02:14:37" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "jquery-pjax" },
            { "v" : "https://github.com/defunkt/jquery-pjax" },
            { "v" : "pushState + ajax = pjax" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/defunkt/jquery-pjax/issues/181#issuecomment-8372284" },
            { "v" : "2012-09-07 17:26:23" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "jquery-pjax" },
            { "v" : "https://github.com/defunkt/jquery-pjax" },
            { "v" : "pushState + ajax = pjax" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/defunkt/jquery-pjax/issues/181#issuecomment-8370383" },
            { "v" : "2012-09-07 16:20:08" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "jquery-pjax" },
            { "v" : "https://github.com/defunkt/jquery-pjax" },
            { "v" : "pushState + ajax = pjax" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/defunkt/jquery-pjax/issues/181#issuecomment-8356401" },
            { "v" : "2012-09-07 05:26:07" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/issues/1568#issuecomment-8338144" },
            { "v" : "2012-09-06 16:21:21" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "jquery-pjax" },
            { "v" : "https://github.com/defunkt/jquery-pjax" },
            { "v" : "pushState + ajax = pjax" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/defunkt/jquery-pjax/issues/181#issuecomment-8332738" },
            { "v" : "2012-09-06 13:51:49" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/issues/1568#issuecomment-8322031" },
            { "v" : "2012-09-06 04:15:41" }
          ] },
      { "f" : [ { "v" : "IssuesEvent" },
            { "v" : "sagarsane" },
            { "v" : "opened" },
            { "v" : "" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/issues/1568" },
            { "v" : "2012-09-06 03:59:46" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "jquery-pjax" },
            { "v" : "https://github.com/defunkt/jquery-pjax" },
            { "v" : "pushState + ajax = pjax" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/defunkt/jquery-pjax/issues/181#issuecomment-8310756" },
            { "v" : "2012-09-05 19:23:22" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "android" },
            { "v" : "https://github.com/github/android" },
            { "v" : "GitHub Android App" },
            { "v" : "Java" },
            { "v" : "https://github.com/github/android/issues/212#issuecomment-8265193" },
            { "v" : "2012-09-04 14:38:49" }
          ] },
      { "f" : [ { "v" : "IssuesEvent" },
            { "v" : "sagarsane" },
            { "v" : "opened" },
            { "v" : "" },
            { "v" : "android" },
            { "v" : "https://github.com/github/android" },
            { "v" : "GitHub Android App" },
            { "v" : "Java" },
            { "v" : "https://github.com/github/android/issues/212" },
            { "v" : "2012-09-04 14:12:20" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/86#issuecomment-8192637" },
            { "v" : "2012-08-31 13:55:54" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/86#issuecomment-8077917" },
            { "v" : "2012-08-28 02:55:47" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/86#issuecomment-8077905" },
            { "v" : "2012-08-28 02:54:57" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "html5-boilerplate" },
            { "v" : "https://github.com/h5bp/html5-boilerplate" },
            { "v" : "A professional front-end template for building fast, robust, and adaptable web apps or sites." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/html5-boilerplate/issues/1179#issuecomment-8065120" },
            { "v" : "2012-08-27 18:19:36" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "html5-boilerplate" },
            { "v" : "https://github.com/h5bp/html5-boilerplate" },
            { "v" : "A professional front-end template for building fast, robust, and adaptable web apps or sites." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/html5-boilerplate/issues/1179#issuecomment-8064452" },
            { "v" : "2012-08-27 18:00:08" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "html5-boilerplate" },
            { "v" : "https://github.com/h5bp/html5-boilerplate" },
            { "v" : "A professional front-end template for building fast, robust, and adaptable web apps or sites." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/html5-boilerplate/issues/1179#issuecomment-8064399" },
            { "v" : "2012-08-27 17:58:44" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "Metro-UI-CSS" },
            { "v" : "https://github.com/olton/Metro-UI-CSS" },
            { "v" : "CSS styles for build Windows 8 Metro UI stylable interface" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/olton/Metro-UI-CSS/issues/17#issuecomment-8064045" },
            { "v" : "2012-08-27 17:48:54" }
          ] },
      { "f" : [ { "v" : "IssuesEvent" },
            { "v" : "sagarsane" },
            { "v" : "opened" },
            { "v" : "" },
            { "v" : "Metro-UI-CSS" },
            { "v" : "https://github.com/olton/Metro-UI-CSS" },
            { "v" : "CSS styles for build Windows 8 Metro UI stylable interface" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/olton/Metro-UI-CSS/issues/17" },
            { "v" : "2012-08-27 14:21:48" }
          ] },
      { "f" : [ { "v" : "IssuesEvent" },
            { "v" : "sagarsane" },
            { "v" : "opened" },
            { "v" : "" },
            { "v" : "Metro-UI-CSS" },
            { "v" : "https://github.com/olton/Metro-UI-CSS" },
            { "v" : "CSS styles for build Windows 8 Metro UI stylable interface" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/olton/Metro-UI-CSS/issues/16" },
            { "v" : "2012-08-27 14:18:23" }
          ] },
      { "f" : [ { "v" : "IssuesEvent" },
            { "v" : "sagarsane" },
            { "v" : "opened" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/86" },
            { "v" : "2012-08-23 20:29:43" }
          ] },
      { "f" : [ { "v" : "PullRequestEvent" },
            { "v" : "sagarsane" },
            { "v" : "opened" },
            { "v" : "Fixed the minor file reference issues in HTML files in new-demo" },
            { "v" : "Metro-UI-CSS" },
            { "v" : "https://github.com/olton/Metro-UI-CSS" },
            { "v" : "CSS styles for build Windows 8 Metro UI stylable interface" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/olton/Metro-UI-CSS/pull/14" },
            { "v" : "2012-08-20 01:59:07" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "Metro-UI-CSS" },
            { "v" : "https://github.com/olton/Metro-UI-CSS" },
            { "v" : "CSS styles for build Windows 8 Metro UI stylable interface" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/olton/Metro-UI-CSS/issues/13#issuecomment-7854624" },
            { "v" : "2012-08-19 16:49:10" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "Metro-UI-CSS" },
            { "v" : "https://github.com/olton/Metro-UI-CSS" },
            { "v" : "CSS styles for build Windows 8 Metro UI stylable interface" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/olton/Metro-UI-CSS/issues/13#issuecomment-7854446" },
            { "v" : "2012-08-19 16:27:34" }
          ] },
      { "f" : [ { "v" : "IssuesEvent" },
            { "v" : "sagarsane" },
            { "v" : "opened" },
            { "v" : "" },
            { "v" : "Metro-UI-CSS" },
            { "v" : "https://github.com/olton/Metro-UI-CSS" },
            { "v" : "CSS styles for build Windows 8 Metro UI stylable interface" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/olton/Metro-UI-CSS/issues/13" },
            { "v" : "2012-08-19 16:04:46" }
          ] }
    ],
  "totalRows" : "85"
}



class Handler(webapp2.RequestHandler):
    
    def write(self, *a, **kw):
        self.response.out.write(*a, **kw)

    def render_str(self, template, **params):
        t = jinja_env.get_template(template)
        return t.render(params)

    def render(self, template, **kw):
        self.write(self.render_str(template, **kw))

    def render_front(self, template):
        self.render(template)        
        
class MainPage(Handler):
    def get(self):
        self.render_front("index.html")

class Experience(Handler):
    def get(self):
        self.response.headers['Content-Type'] = 'application/json'
        self.write(json.dumps(get_gist_data('3735396','experience_data')))
        
class Education(Handler):
    def get(self):
        self.response.headers['Content-Type'] = 'application/json' 
        self.write(json.dumps(get_gist_data('3735401','education_data')))
        
class Projects(Handler):
    def get(self):
        self.response.headers['Content-Type'] = 'application/json'
        self.write(json.dumps(get_gist_data('3734919','projects_data')))

class Contact(Handler):
    def get(self):
        self.response.headers['Content-Type'] = 'application/json'
        self.write(json.dumps(get_gist_data('3785786','contact_data')))

class Achievements(Handler):
    def get(self):
        self.response.headers['Content-Type'] = 'application/json'
        self.write(json.dumps(get_gist_data('3785895','achievements_data')))

class GithubActivity(Handler):
    def get(self):
        activity = {}
        entries = []
        user = setUser("<username>", "<password>")
        entries = entries + getFollowers(user)
        entries = entries + getFollowing(user)
        entries = entries + getWatchedRepos(user)
        activity['activities'] = entries
        self.response.headers['Content-Type'] = 'application/json'
        self.write(json.dumps(activity))

class GithubArchiveHTML(Handler):
    def get(self):
        #self.render_front("timeline.html")
        self.rendor_front("metro_github_archive.html")
                
class GithubArchiveBigQuery(Handler):
    def get(self):
        #service = build("bigquery", "v2", http=http)
        self.response.headers['Content-Type'] = 'application/json'
        #parsed_archive = parser(execute_bigquery_githubarchive(service))
        parsed_archive = parser(arch=archive)
        self.write(json.dumps(parsed_archive))
        
app = webapp2.WSGIApplication([('/', MainPage),
                               ('/home', MainPage),                                
                               ('/projects', Projects), 
                               ('/experience', Experience),
                               ('/education', Education),
                               ('/contact', Contact),
                               ('/achievements', Achievements),
                               ('/github_activity', GithubActivity),
                               ('/github_archive', GithubArchiveHTML),
                               ('/archive_data', GithubArchiveBigQuery)], debug=True)