'''
Created on Oct 1, 2012

@author: Sagar
'''

import httplib2
import json
from apiclient.discovery import build
from oauth2client.appengine import AppAssertionCredentials

from mainhandler import Handler
from ..utilities.github_archive_bigquery_handler import execute_bigquery_githubarchive

local_archive = { "etag" : "\"viowSXH0JIvMREGVicRUeTw4PZo/LPUtui-L1gif2w5oh2hCk24cZ-I\"",
  "kind" : "bigquery#tableDataList",
  "pageToken" : "89@1351390966098",
  "rows" : [ { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "Metro-UI-CSS" },
            { "v" : "https://github.com/olton/Metro-UI-CSS" },
            { "v" : "CSS styles for build Windows 8 Metro UI stylable interface" },
            { "v" : "PHP" },
            { "v" : "https://github.com/olton/Metro-UI-CSS/issues/25#issuecomment-9306865" },
            { "v" : "2012-10-10 15:19:34" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/issues/1706#issuecomment-9288708" },
            { "v" : "2012-10-10 03:07:47" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/96#issuecomment-9194883" },
            { "v" : "2012-10-06 03:33:13" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/96#issuecomment-9183761" },
            { "v" : "2012-10-05 17:43:13" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/issues/1706#issuecomment-9129351" },
            { "v" : "2012-10-04 03:06:19" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/issues/1599#issuecomment-9073980" },
            { "v" : "2012-10-02 15:02:25" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/issues/1706#issuecomment-9017348" },
            { "v" : "2012-09-30 20:07:49" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "version.is" },
            { "v" : "https://github.com/gustavnikolaj/version.is" },
            { "v" : "version.is: Single-page app and API for version checking of Open Source projects" },
            { "v" : "Python" },
            { "v" : "https://github.com/gustavnikolaj/version.is/issues/19#issuecomment-9003489" },
            { "v" : "2012-09-29 12:23:12" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "version.is" },
            { "v" : "https://github.com/gustavnikolaj/version.is" },
            { "v" : "version.is: Single-page app and API for version checking of Open Source projects" },
            { "v" : "Python" },
            { "v" : "https://github.com/gustavnikolaj/version.is/issues/19#issuecomment-9003313" },
            { "v" : "2012-09-29 11:59:20" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "version.is" },
            { "v" : "https://github.com/gustavnikolaj/version.is" },
            { "v" : "version.is: Single-page app and API for version checking of Open Source projects" },
            { "v" : "Python" },
            { "v" : "https://github.com/gustavnikolaj/version.is/issues/19#issuecomment-9000930" },
            { "v" : "2012-09-29 05:11:44" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/issues/1706#issuecomment-8961790" },
            { "v" : "2012-09-28 02:35:28" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/issues/1706#issuecomment-8842131" },
            { "v" : "2012-09-25 03:02:11" }
          ] },
      { "f" : [ { "v" : "PullRequestEvent" },
            { "v" : "sagarsane" },
            { "v" : "opened" },
            { "v" : "Committing fix for Issue 1705" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/pull/1706" },
            { "v" : "2012-09-23 21:10:07" }
          ] },
      { "f" : [ { "v" : "IssuesEvent" },
            { "v" : "sagarsane" },
            { "v" : "opened" },
            { "v" : "" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/issues/1705" },
            { "v" : "2012-09-23 20:54:40" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/issues/1700#issuecomment-8802086" },
            { "v" : "2012-09-23 19:49:02" }
          ] },
      { "f" : [ { "v" : "IssuesEvent" },
            { "v" : "sagarsane" },
            { "v" : "opened" },
            { "v" : "" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/issues/1700" },
            { "v" : "2012-09-22 19:37:10" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "TimelineJS" },
            { "v" : "https://github.com/VeriteCo/TimelineJS" },
            { "v" : "TimelineJS: A Storytelling Timeline built in JavaScript." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/VeriteCo/TimelineJS/issues/208#issuecomment-8781025" },
            { "v" : "2012-09-21 21:29:11" }
          ] },
      { "f" : [ { "v" : "IssuesEvent" },
            { "v" : "sagarsane" },
            { "v" : "opened" },
            { "v" : "" },
            { "v" : "android" },
            { "v" : "https://github.com/github/android" },
            { "v" : "GitHub Android App" },
            { "v" : "Java" },
            { "v" : "https://github.com/github/android/issues/231" },
            { "v" : "2012-09-20 17:19:43" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "android" },
            { "v" : "https://github.com/github/android" },
            { "v" : "GitHub Android App" },
            { "v" : "Java" },
            { "v" : "https://github.com/github/android/issues/229#issuecomment-8711619" },
            { "v" : "2012-09-19 23:00:25" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "android" },
            { "v" : "https://github.com/github/android" },
            { "v" : "GitHub Android App" },
            { "v" : "Java" },
            { "v" : "https://github.com/github/android/issues/229#issuecomment-8704437" },
            { "v" : "2012-09-19 19:58:45" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "android" },
            { "v" : "https://github.com/github/android" },
            { "v" : "GitHub Android App" },
            { "v" : "Java" },
            { "v" : "https://github.com/github/android/issues/229#issuecomment-8704251" },
            { "v" : "2012-09-19 19:52:45" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "version.is" },
            { "v" : "https://github.com/gustavnikolaj/version.is" },
            { "v" : "version.is: Single-page app and API for version checking of Open Source projects" },
            { "v" : "Python" },
            { "v" : "https://github.com/gustavnikolaj/version.is/issues/17#issuecomment-8690755" },
            { "v" : "2012-09-19 13:22:33" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/86#issuecomment-8678959" },
            { "v" : "2012-09-19 04:25:50" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/86#issuecomment-8667852" },
            { "v" : "2012-09-18 19:51:09" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "version.is" },
            { "v" : "https://github.com/gustavnikolaj/version.is" },
            { "v" : "version.is: Single-page app and API for version checking of Open Source projects" },
            { "v" : "Python" },
            { "v" : "https://github.com/gustavnikolaj/version.is/issues/5#issuecomment-8656929" },
            { "v" : "2012-09-18 14:37:26" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "version.is" },
            { "v" : "https://github.com/gustavnikolaj/version.is" },
            { "v" : "version.is: Single-page app and API for version checking of Open Source projects" },
            { "v" : "Python" },
            { "v" : "https://github.com/gustavnikolaj/version.is/issues/5#issuecomment-8655315" },
            { "v" : "2012-09-18 13:48:36" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "version.is" },
            { "v" : "https://github.com/gustavnikolaj/version.is" },
            { "v" : "version.is: Single-page app and API for version checking of Open Source projects" },
            { "v" : "Python" },
            { "v" : "https://github.com/gustavnikolaj/version.is/issues/5#issuecomment-8653003" },
            { "v" : "2012-09-18 12:46:40" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "version.is" },
            { "v" : "https://github.com/gustavnikolaj/version.is" },
            { "v" : "version.is: Single-page app and API for version checking of Open Source projects" },
            { "v" : "Python" },
            { "v" : "https://github.com/gustavnikolaj/version.is/issues/5#issuecomment-8651787" },
            { "v" : "2012-09-18 12:16:48" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/86#issuecomment-8638751" },
            { "v" : "2012-09-18 03:20:04" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "version.is" },
            { "v" : "https://github.com/gustavnikolaj/version.is" },
            { "v" : "version.is: Single-page app and API for version checking of Open Source projects" },
            { "v" : "Python" },
            { "v" : "https://github.com/gustavnikolaj/version.is/issues/5#issuecomment-8637719" },
            { "v" : "2012-09-18 02:19:00" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "version.is" },
            { "v" : "https://github.com/gustavnikolaj/version.is" },
            { "v" : "version.is: Single-page app and API for version checking of Open Source projects" },
            { "v" : "Python" },
            { "v" : "https://github.com/gustavnikolaj/version.is/issues/5#issuecomment-8637552" },
            { "v" : "2012-09-18 02:09:27" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "version.is" },
            { "v" : "https://github.com/gustavnikolaj/version.is" },
            { "v" : "version.is: Single-page app and API for version checking of Open Source projects" },
            { "v" : "Python" },
            { "v" : "https://github.com/gustavnikolaj/version.is/issues/8#issuecomment-8630511" },
            { "v" : "2012-09-17 20:54:14" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "version.is" },
            { "v" : "https://github.com/gustavnikolaj/version.is" },
            { "v" : "version.is: Single-page app and API for version checking of Open Source projects" },
            { "v" : "Python" },
            { "v" : "https://github.com/gustavnikolaj/version.is/issues/11#issuecomment-8616302" },
            { "v" : "2012-09-17 14:23:43" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "version.is" },
            { "v" : "https://github.com/gustavnikolaj/version.is" },
            { "v" : "version.is: Single-page app and API for version checking of Open Source projects" },
            { "v" : "Python" },
            { "v" : "https://github.com/gustavnikolaj/version.is/issues/11#issuecomment-8616059" },
            { "v" : "2012-09-17 14:19:22" }
          ] },
      { "f" : [ { "v" : "IssuesEvent" },
            { "v" : "sagarsane" },
            { "v" : "opened" },
            { "v" : "" },
            { "v" : "version.is" },
            { "v" : "https://github.com/gustavnikolaj/version.is" },
            { "v" : "version.is: Single-page app and API for version checking of Open Source projects" },
            { "v" : "Python" },
            { "v" : "https://github.com/gustavnikolaj/version.is/issues/11" },
            { "v" : "2012-09-17 01:11:18" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/86#issuecomment-8601833" },
            { "v" : "2012-09-16 23:56:22" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/86#issuecomment-8597355" },
            { "v" : "2012-09-16 18:21:01" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/86#issuecomment-8596908" },
            { "v" : "2012-09-16 17:40:20" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/86#issuecomment-8596166" },
            { "v" : "2012-09-16 16:21:02" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "android" },
            { "v" : "https://github.com/github/android" },
            { "v" : "GitHub Android App" },
            { "v" : "Java" },
            { "v" : "https://github.com/github/android/issues/222#issuecomment-8591896" },
            { "v" : "2012-09-16 03:10:49" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "android" },
            { "v" : "https://github.com/github/android" },
            { "v" : "GitHub Android App" },
            { "v" : "Java" },
            { "v" : "https://github.com/github/android/issues/222#issuecomment-8591535" },
            { "v" : "2012-09-16 01:59:06" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/96#issuecomment-8541227" },
            { "v" : "2012-09-13 20:02:37" }
          ] },
      { "f" : [ { "v" : "IssuesEvent" },
            { "v" : "sagarsane" },
            { "v" : "opened" },
            { "v" : "" },
            { "v" : "version.is" },
            { "v" : "https://github.com/gustavnikolaj/version.is" },
            { "v" : "version.is: Single-page app and API for version checking of Open Source projects" },
            { "v" : "Python" },
            { "v" : "https://github.com/gustavnikolaj/version.is/issues/8" },
            { "v" : "2012-09-13 18:01:42" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/96#issuecomment-8537109" },
            { "v" : "2012-09-13 17:58:31" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/issues/1599#issuecomment-8536311" },
            { "v" : "2012-09-13 17:33:29" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/96#issuecomment-8536152" },
            { "v" : "2012-09-13 17:28:22" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/96#issuecomment-8534454" },
            { "v" : "2012-09-13 16:35:56" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "version.is" },
            { "v" : "https://github.com/gustavnikolaj/version.is" },
            { "v" : "version.is: Single-page app and API for version checking of Open Source projects" },
            { "v" : "Python" },
            { "v" : "https://github.com/gustavnikolaj/version.is/issues/3#issuecomment-8531840" },
            { "v" : "2012-09-13 15:19:03" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/issues/1598#issuecomment-8503337" },
            { "v" : "2012-09-12 17:41:14" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/96#issuecomment-8503185" },
            { "v" : "2012-09-12 17:36:54" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/96#issuecomment-8495254" },
            { "v" : "2012-09-12 14:25:17" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "PyGithub" },
            { "v" : "https://github.com/jacquev6/PyGithub" },
            { "v" : "Python library implementing the full Github API v3" },
            { "v" : "Python" },
            { "v" : "https://github.com/jacquev6/PyGithub/issues/82#issuecomment-8494716" },
            { "v" : "2012-09-12 14:09:46" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/86#issuecomment-8481792" },
            { "v" : "2012-09-12 04:27:59" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/86#issuecomment-8481457" },
            { "v" : "2012-09-12 04:05:31" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/issues/1568#issuecomment-8465467" },
            { "v" : "2012-09-11 17:21:42" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/86#issuecomment-8459797" },
            { "v" : "2012-09-11 13:38:57" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/86#issuecomment-8446860" },
            { "v" : "2012-09-11 04:36:24" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/86#issuecomment-8446340" },
            { "v" : "2012-09-11 03:53:15" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/issues/1597#issuecomment-8444690" },
            { "v" : "2012-09-11 01:55:07" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "lazyweb-requests" },
            { "v" : "https://github.com/h5bp/lazyweb-requests" },
            { "v" : "Get projects and ideas built by the community" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/h5bp/lazyweb-requests/issues/86#issuecomment-8435011" },
            { "v" : "2012-09-10 19:21:19" }
          ] },
      { "f" : [ { "v" : "PullRequestReviewCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/pull/1599#discussion_r1568385" },
            { "v" : "2012-09-10 17:36:33" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "jquery-pjax" },
            { "v" : "https://github.com/defunkt/jquery-pjax" },
            { "v" : "pushState + ajax = pjax" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/defunkt/jquery-pjax/issues/184#issuecomment-8426208" },
            { "v" : "2012-09-10 15:18:33" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "jquery-pjax" },
            { "v" : "https://github.com/defunkt/jquery-pjax" },
            { "v" : "pushState + ajax = pjax" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/defunkt/jquery-pjax/issues/184#issuecomment-8425244" },
            { "v" : "2012-09-10 14:55:07" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "jquery-pjax" },
            { "v" : "https://github.com/defunkt/jquery-pjax" },
            { "v" : "pushState + ajax = pjax" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/defunkt/jquery-pjax/issues/181#issuecomment-8410922" },
            { "v" : "2012-09-10 00:04:47" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "jquery-pjax" },
            { "v" : "https://github.com/defunkt/jquery-pjax" },
            { "v" : "pushState + ajax = pjax" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/defunkt/jquery-pjax/issues/181#issuecomment-8410250" },
            { "v" : "2012-09-09 22:39:46" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "jquery-pjax" },
            { "v" : "https://github.com/defunkt/jquery-pjax" },
            { "v" : "pushState + ajax = pjax" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/defunkt/jquery-pjax/issues/181#issuecomment-8410212" },
            { "v" : "2012-09-09 22:35:13" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "jquery-pjax" },
            { "v" : "https://github.com/defunkt/jquery-pjax" },
            { "v" : "pushState + ajax = pjax" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/defunkt/jquery-pjax/issues/181#issuecomment-8409789" },
            { "v" : "2012-09-09 21:50:27" }
          ] },
      { "f" : [ { "v" : "PullRequestReviewCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/pull/1599#discussion_r1561449" },
            { "v" : "2012-09-09 04:44:50" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/issues/1599#issuecomment-8397297" },
            { "v" : "2012-09-08 20:04:01" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "jquery-pjax" },
            { "v" : "https://github.com/defunkt/jquery-pjax" },
            { "v" : "pushState + ajax = pjax" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/defunkt/jquery-pjax/issues/181#issuecomment-8391206" },
            { "v" : "2012-09-08 16:52:12" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "jquery-pjax" },
            { "v" : "https://github.com/defunkt/jquery-pjax" },
            { "v" : "pushState + ajax = pjax" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/defunkt/jquery-pjax/issues/181#issuecomment-8388359" },
            { "v" : "2012-09-08 15:00:55" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "jquery-pjax" },
            { "v" : "https://github.com/defunkt/jquery-pjax" },
            { "v" : "pushState + ajax = pjax" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/defunkt/jquery-pjax/issues/181#issuecomment-8387596" },
            { "v" : "2012-09-08 13:30:37" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/issues/1598#issuecomment-8384978" },
            { "v" : "2012-09-08 06:14:58" }
          ] },
      { "f" : [ { "v" : "PullRequestEvent" },
            { "v" : "sagarsane" },
            { "v" : "opened" },
            { "v" : "Added search query in search results label for 'Find In Files'" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/pull/1599" },
            { "v" : "2012-09-08 06:13:55" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/issues/1598#issuecomment-8384917" },
            { "v" : "2012-09-08 06:01:03" }
          ] },
      { "f" : [ { "v" : "IssuesEvent" },
            { "v" : "sagarsane" },
            { "v" : "opened" },
            { "v" : "" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/issues/1598" },
            { "v" : "2012-09-08 05:31:23" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/issues/1597#issuecomment-8384745" },
            { "v" : "2012-09-08 05:25:36" }
          ] },
      { "f" : [ { "v" : "IssuesEvent" },
            { "v" : "sagarsane" },
            { "v" : "opened" },
            { "v" : "" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/issues/1597" },
            { "v" : "2012-09-08 05:12:58" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "jquery-pjax" },
            { "v" : "https://github.com/defunkt/jquery-pjax" },
            { "v" : "pushState + ajax = pjax" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/defunkt/jquery-pjax/issues/181#issuecomment-8383760" },
            { "v" : "2012-09-08 02:14:37" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "jquery-pjax" },
            { "v" : "https://github.com/defunkt/jquery-pjax" },
            { "v" : "pushState + ajax = pjax" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/defunkt/jquery-pjax/issues/181#issuecomment-8372284" },
            { "v" : "2012-09-07 17:26:23" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "jquery-pjax" },
            { "v" : "https://github.com/defunkt/jquery-pjax" },
            { "v" : "pushState + ajax = pjax" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/defunkt/jquery-pjax/issues/181#issuecomment-8370383" },
            { "v" : "2012-09-07 16:20:08" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "jquery-pjax" },
            { "v" : "https://github.com/defunkt/jquery-pjax" },
            { "v" : "pushState + ajax = pjax" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/defunkt/jquery-pjax/issues/181#issuecomment-8356401" },
            { "v" : "2012-09-07 05:26:07" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/issues/1568#issuecomment-8338144" },
            { "v" : "2012-09-06 16:21:21" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "jquery-pjax" },
            { "v" : "https://github.com/defunkt/jquery-pjax" },
            { "v" : "pushState + ajax = pjax" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/defunkt/jquery-pjax/issues/181#issuecomment-8332738" },
            { "v" : "2012-09-06 13:51:49" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/issues/1568#issuecomment-8322031" },
            { "v" : "2012-09-06 04:15:41" }
          ] },
      { "f" : [ { "v" : "IssuesEvent" },
            { "v" : "sagarsane" },
            { "v" : "opened" },
            { "v" : "" },
            { "v" : "brackets" },
            { "v" : "https://github.com/adobe/brackets" },
            { "v" : "An open source code editor for the web, written in JavaScript, HTML and CSS." },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/adobe/brackets/issues/1568" },
            { "v" : "2012-09-06 03:59:46" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "jquery-pjax" },
            { "v" : "https://github.com/defunkt/jquery-pjax" },
            { "v" : "pushState + ajax = pjax" },
            { "v" : "JavaScript" },
            { "v" : "https://github.com/defunkt/jquery-pjax/issues/181#issuecomment-8310756" },
            { "v" : "2012-09-05 19:23:22" }
          ] },
      { "f" : [ { "v" : "IssueCommentEvent" },
            { "v" : "sagarsane" },
            { "v" : "" },
            { "v" : "" },
            { "v" : "android" },
            { "v" : "https://github.com/github/android" },
            { "v" : "GitHub Android App" },
            { "v" : "Java" },
            { "v" : "https://github.com/github/android/issues/212#issuecomment-8265193" },
            { "v" : "2012-09-04 14:38:49" }
          ] },
      { "f" : [ { "v" : "IssuesEvent" },
            { "v" : "sagarsane" },
            { "v" : "opened" },
            { "v" : "" },
            { "v" : "android" },
            { "v" : "https://github.com/github/android" },
            { "v" : "GitHub Android App" },
            { "v" : "Java" },
            { "v" : "https://github.com/github/android/issues/212" },
            { "v" : "2012-09-04 14:12:20" }
          ] }
    ],
  "totalRows" : "89"
}
credentials = AppAssertionCredentials(scope='https://www.googleapis.com/auth/bigquery')
http = credentials.authorize(httplib2.Http())

def parser(arch):
    archive = arch
    
    data = {}
    timeline = {}
    timeline['headline'] = "My Open Source Contribution Archive"
    timeline['type'] = "default"
    timeline['text'] = "<p>This is my Github Archive for past 1 Month! (user: <strong>sagarsane</strong>)</p>"
    timeline['asset'] = {
                        "media":"http://www.github.com/sagarsane/abetterportfolio",
                        "credit":"Sagar Sane",
                        "caption":"Part of: A Betterportfolio project"
                         }
    info = []
    era_info = [{
                 "startDate":"",
                 "endDate":"",
                 "headline":"",
                 "tag":"",
                 }]
    chart_info = [{
                 "startDate":"",
                 "endDate":"",
                 "headline":"",
                 "tag":"",
                 }]
    
    

    
    split_start_date = archive.get('rows')[0]['f'][9]['v'].split(' ')
    happened_date1 = ",".join(split_start_date[0].split("-"))
    happened_date = happened_date1 + "," + ",".join(split_start_date[1].split(":"))
    era_info[0]['endDate'] = chart_info[0]['endDate'] = happened_date
    
    lastRow = int(archive.get('totalRows')) - 1
    split_start_date = archive.get('rows')[lastRow]['f'][9]['v'].split(' ')
    happened_date1 = ",".join(split_start_date[0].split("-"))
    happened_date = happened_date1 + "," + ",".join(split_start_date[1].split(":"))
    era_info[0]['startDate'] = chart_info[0]['startDate'] = happened_date
    
    for row in archive.get('rows'):
        an_info = {
               "startDate" : "",
               "endDate" : "",
               "headline" : "",
               "text" : "",
               "tag" : "",
               "asset" : {
                          "media" : "",
                          "thumbnail" : "",
                          "credit" : "",
                          "caption" : ""
                          },
               }
        columns = row['f']
        an_info['startDate'] = an_info['endDate'] = happened_date
        check_link = columns[8]['v'].split("#")
        if len(check_link) > 0:
            an_info['headline'] = "<a href = '" + columns[8]['v'] + "' target='_blank'>" + columns[0]['v'] + "</a>"
        else:
            an_info['headline'] = "<a href = '" + columns[8]['v'] + "' target='_blank'>" + columns[0]['v'] + "</a>"
        an_info['text'] = columns[4]['v']  + "-" + columns[7]['v']
        an_info['tag'] = columns[0]['v']
        an_info['asset']['caption'] = "<a href = '" + columns[8]['v'] + "' target='_blank'></a>"
        an_info['asset']['credit'] = columns[6]['v']
        #+ columns[5]['v'] + " - " + columns[6]['v']
        split_date = columns[9]['v'].split(' ')
        happened_date1 = ",".join(split_date[0].split("-"))
        happened_date = happened_date1 + "," + ",".join(split_date[1].split(":"))
        info.append(an_info)
        
    timeline['date'] = info
    timeline['era'] = era_info
    timeline['chart'] = chart_info
    data['timeline'] = timeline
    return data


class GithubArchiveHTML(Handler):
    def get(self):
        #self.render_front("timeline.html")                
        self.render("metro_github_archive.html")
        
class GithubArchiveBigQuery(Handler):
    def get(self):
        self.response.headers['Content-Type'] = 'application/json'
        """Local_parser_result"""
        self.write(json.dumps(local_archive))
        
        """Remote_parser_result
        service = build("bigquery", "v2", http=http)        
        parsed_archive = execute_bigquery_githubarchive(service)
        self.write(json.dumps(parsed_archive))
        """